### ISSUE TITLE
Making Dismod-AT and Cascade-AT versions dynamic arguments to docker build script

### ISSUE THREAD

**Issue by davidshaw2018** [bradbell/dismod_at#5]
Hi @bradbell,

I'm trying to build a Jenkins pipeline that can create and deploy a new Dismod-AT container, I was going to use your build suite but I noticed that it seems the versions are hardcoded: 
https://github.com/bradbell/dismod_at/blob/master/bin/dock_dismod_at.sh#L90-L98

Would it be possible to make the dismod-at and cascade-at versions arguments instead to dock_dismod_at? Otherwise it's hard for users other than yourself to build a more recent version of dismod at. 

As a follow up, is it possible to tag releases? This would spare you the trouble of looking up specific git hashes as well. 

If you don't have the bandwidth to address, I'm happy to make a PR myself if you want.

**Comment by bradbell** [comment]
at_cascade releases can be found at test.pypi.org
https://test.pypi.org/project/at-cascade/
The test directory is being used because it is under heavy development.
This requires dismod_at to be installed separately.

at_cascade uses dismod_at which uses cppad_mixed which uses cppad.
cppad releases can be found at
https://github.com/coin-or/CppAD/tags

The problem here is that sometimes I make an improvement to CppAD tor cppad_mixed hat I need right away in dismod_at. 
The version of CppAD currently required by cppad_mixed is 20220518. The last stable release is 20220000.4
See git_hash in
https://github.com/bradbell/cppad_mixed/blob/master/bin/install_cppad.sh
For this reason I have gone to a git hash method for the corresponding releases for dismod_at development.

The way I have been using release by hash is as follows:

dismod_at specifies a version of cppad_mixed that it works with by its git_hash. 
That version of cppad_mixed specifies its version of CppAD by a git_hash.
These hashes have a corresponding version date to make it easier for a human to understand.

If you checkout the current master branch of  dismod_at, and use dock_dismod_at.sh, you will be getting the most recent release of dismod_at. 

If you want an older release, you can checkout a git_hash corresponding to an older version of the master and use the corresponding dock_dismod_at.sh.

For a Jenkins pipline, for each check in of the master, I would check if dock_dismod_at.sh has changed and if so, I would run the corresponding tests etc.

Does that make sence to you ?

**Comment by bradbell** [comment]
As a side comment, if one is using the most recent version of at_cascade (on the test.pypi.org) they should  use the dismod_at image provided by dock_dismod_at.sh (not the at_cascade image).

**Comment by davidshaw2018** [comment]
So what I'm hearing is that basically we can count on you updating these hashes manually if the dismod AT version of CppAD versions update? If we can assume that dock_dismod always points to the latest version then I think I can go ahead with the first iteration. 

I'm still a little confused about why this is the preferred versioning scheme versus standard semantic versioning (e.g. 1.2.0, 1.3.0, 1.3.1, etc) with git tags, but that's not critical to address immediately

**Comment by bradbell** [comment]
Here is my preferred way to do releases:

1. I  use dates in versions so that it is easy to keep track of features versus version numbers. For example see
    https://coin-or.github.io/CppAD/doc/whats_new_22.htm

2. I cut a new stable version once a year by creating a stable branch. For example see
   https://github.com/coin-or/CppAD/tree/stable/20220000

3. Only bug fixes, and not feature changes, are made to the stable version. The corresponding releases have the same date and  an extra index to make them unique. For example, see
   https://github.com/coin-or/CppAD/tags

i use the git-hash method of specifying versions when I require releases more often than once a year. This has the advantage of being able to include recent additional features. It has the disadvantage of not using stable versions with only bug fixes.

**Comment by bradbell** [comment]
> So what I'm hearing is that basically we can count on you updating these hashes manually if the dismod AT version of CppAD versions update? If we can assume that dock_dismod always points to the latest version then I think I can go 

Yes. When I cut a new version of dock_dismod_at.sh I may or may not update the projects that it depends on. I test all of this before committing the change. There is an important point here, the git hash in dock_dismod_at.sh refers to a point before dock_dismod_at.sh is committed. I test dock_dismod_at.sh with this hash and then commit it.

**Comment by davidshaw2018** [comment]
Great, thanks Brad!

**Comment by bradbell** [comment]
For now, please  build the image using
```
usage: dock_dismod_at.sh image base
usage: dock_dismod_at.sh image mixed
usage: dock_dismod_at.sh image dismod_at
```
and not using
```
dock_dismod_at.sh image at_cascade
```
So that we will be able to update at_cascade using pip in the dismod_at image. 
Once at_cascade becomes more stable, we can include it in the image.

Thanks !!
